export const gameData = [
  {
    name: "Alchemy Gold",
    rtp: "96.78%",
    maxExposure: "x2992",
    minBet: "0.2",
    provider: "PG SOFT",
  },
  {
    name: "Anubis Wrath",
    rtp: "96.75%",
    maxExposure: "x10000",
    minBet: "0.2",
    provider: "PG SOFT",
  },
  {
    name: "Asgardian Rising",
    rtp: "96.76%",
    maxExposure: "x8305",
    minBet: "0.2",
    provider: "PG SOFT",
  },
  {
    name: "Baccarat Deluxe",
    rtp: "98.94% (Traditional), 98.76% (Super Six)",
    maxExposure: "x11",
    minBet:
      "Low Limit\nSuper 6/player pair/banker pair: 1\nBanker/Player: 1\nDraw: 1\n\nMID Limit\nSuper 6/player pair/banker pair: 10\nBanker/Player: 10\nDraw: 10\n\nHigh Limit\nSuper 6/player pair/banker pair: 50\nBanker/Player: 50\nDraw: 50",
    provider: "PG SOFT",
  },
  {
    name: "Bakery Bonanza",
    rtp: "96.72%",
    maxExposure: "x12190",
    minBet: "0.2",
    provider: "PG SOFT",
  },
  {
    name: "Bali Vacation",
    rtp: "96.71%",
    maxExposure: "x3560",
    minBet: "0.2",
    provider: "PG SOFT",
  },
  {
    name: "Battleground Royale",
    rtp: "96.75%",
    maxExposure: "x1690",
    minBet: "0.2",
    provider: "PG SOFT",
  },
  {
    name: "Bikini Paradise",
    rtp: "96.95%",
    maxExposure: "x5482",
    minBet: "0.25",
    provider: "PG SOFT",
  },
  {
    name: "Buffalo Win",
    rtp: "96.71%",
    maxExposure: "x1548",
    minBet: "0.2",
    provider: "PG SOFT",
  },
  {
    name: "Butterfly Blossom",
    rtp: "96.74%",
    maxExposure: "x7125",
    minBet: "0.2",
    provider: "PG SOFT",
  },
  {
    name: "Caishen Wins",
    rtp: "96.92%",
    maxExposure: "x4936",
    minBet: "0.2",
    provider: "PG SOFT",
  },
  {
    name: "Candy Bonanza",
    rtp: "96.72%",
    maxExposure: "x2563",
    minBet: "0.2",
    provider: "PG SOFT",
  },
  {
    name: "Candy Burst",
    rtp: "96.95%",
    maxExposure: "x1016",
    minBet: "0.2",
    provider: "PG SOFT",
  },
  {
    name: "Captain's Bounty",
    rtp: "96.15%",
    maxExposure: "x4796",
    minBet: "0.2",
    provider: "PG SOFT",
  },
  {
    name: "Cash Mania",
    rtp: "96.75%",
    maxExposure: "x2000",
    minBet: "0.2",
    provider: "PG SOFT",
  },
  {
    name: "Circus Delight",
    rtp: "96.70%",
    maxExposure: "x5467",
    minBet: "0.25",
    provider: "PG SOFT",
  },
  {
    name: "Cocktail Nights",
    rtp: "96.75%",
    maxExposure: "x5173",
    minBet: "0.2",
    provider: "PG SOFT",
  },
  {
    name: "Cruise Royale",
    rtp: "96.63%",
    maxExposure: "x2500",
    minBet: "0.2",
    provider: "PG SOFT",
  },
  {
    name: "Crypto Gold",
    rtp: "96.71%",
    maxExposure: "x8329",
    minBet: "0.2",
    provider: "PG SOFT",
  },
  {
    name: "Destiny of Sun & Moon",
    rtp: "96.80%",
    maxExposure: "x3913",
    minBet: "0.2",
    provider: "PG SOFT",
  },
  {
    name: "Diner Delights",
    rtp: "96.75%",
    maxExposure: "x2989",
    minBet: "0.2",
    provider: "PG SOFT",
  },
  {
    name: "Double Fortune",
    rtp: "96.22%",
    maxExposure: "x6165",
    minBet: "0.3",
    provider: "PG SOFT",
  },
  {
    name: "Dragon Hatch",
    rtp: "96.83%",
    maxExposure: "x2027",
    minBet: "0.2",
    provider: "PG SOFT",
  },
  {
    name: "Dragon Hatch 2",
    rtp: "96.76%",
    maxExposure: "x2500",
    minBet: "0.2",
    provider: "PG SOFT",
  },
  {
    name: "Dragon Legend",
    rtp: "97.15%",
    maxExposure: "x1672",
    minBet: "0.27",
    provider: "PG SOFT",
  },
  {
    name: "Dragon Tiger Luck",
    rtp: "96.94%",
    maxExposure: "x200",
    minBet: "0.25",
    provider: "PG SOFT",
  },
  {
    name: "Dreams of Macau",
    rtp: "96.73%",
    maxExposure: "x6160",
    minBet: "0.2",
    provider: "PG SOFT",
  },
  {
    name: "Egypt's Book of Mystery",
    rtp: "96.75%",
    maxExposure: "x9546",
    minBet: "0.2",
    provider: "PG SOFT",
  },
  {
    name: "Emoji Riches",
    rtp: "96.78%",
    maxExposure: "x2992",
    minBet: "0.2",
    provider: "PG SOFT",
  },
  {
    name: "Emperor's Favour",
    rtp: "96.03%",
    maxExposure: "x639",
    minBet: "0.3",
    provider: "PG SOFT",
  },
  {
    name: "Flirting Scholar",
    rtp: "97.44%",
    maxExposure: "x1407",
    minBet: "0.2",
    provider: "PG SOFT",
  },
  {
    name: "Forge of Wealth",
    rtp: "96.74%",
    maxExposure: "x5000",
    minBet: "0.2",
    provider: "PG SOFT",
  },
  {
    name: "Fortune Dragon",
    rtp: "96.74%",
    maxExposure: "x2500",
    minBet: "0.25",
    provider: "PG SOFT",
  },
  {
    name: "Fortune Gods",
    rtp: "95.04%",
    maxExposure: "x1024",
    minBet: "0.3",
    provider: "PG SOFT",
  },
  {
    name: "Fortune Mouse",
    rtp: "96.96%",
    maxExposure: "x1000",
    minBet: "0.25",
    provider: "PG SOFT",
  },
  {
    name: "Fortune Ox",
    rtp: "96.75%",
    maxExposure: "x2000",
    minBet: "0.2",
    provider: "PG SOFT",
  },
  {
    name: "Fortune Rabbit",
    rtp: "96.75%",
    maxExposure: "x5000",
    minBet: "0.2",
    provider: "PG SOFT",
  },
  {
    name: "Fortune Tiger",
    rtp: "96.81%",
    maxExposure: "x2500",
    minBet: "0.25",
    provider: "PG SOFT",
  },
  {
    name: "Fruity Candy",
    rtp: "96.75%",
    maxExposure: "x10000",
    minBet: "0.2",
    provider: "PG SOFT",
  },
  {
    name: "Futebol Fever",
    rtp: "96.73%",
    maxExposure: "x2000",
    minBet: "0.2",
    provider: "PG SOFT",
  },
  {
    name: "Ganesha Fortune",
    rtp: "96.72%",
    maxExposure: "x7524",
    minBet: "0.2",
    provider: "PG SOFT",
  },
  {
    name: "Ganesha Gold",
    rtp: "96.08%",
    maxExposure: "x4963",
    minBet: "0.3",
    provider: "PG SOFT",
  },
  {
    name: "Garuda Gems",
    rtp: "96.77%",
    maxExposure: "x3136",
    minBet: "0.2",
    provider: "PG SOFT",
  },
  {
    name: "Gem Saviour",
    rtp: "96.82%",
    maxExposure: "x74",
    minBet: "0.3",
    provider: "PG SOFT",
  },
  {
    name: "Gem Saviour Conquest",
    rtp: "96.92%",
    maxExposure: "x7551",
    minBet: "0.2",
    provider: "PG SOFT",
  },
  {
    name: "Gem Saviour Sword",
    rtp: "95.54%",
    maxExposure: "x300",
    minBet: "0.3",
    provider: "PG SOFT",
  },
  {
    name: "Gemstones Gold",
    rtp: "96.71%",
    maxExposure: "x7500",
    minBet: "0.2",
    provider: "PG SOFT",
  },
  {
    name: "Genie's 3 Wishes",
    rtp: "96.75%",
    maxExposure: "x3213",
    minBet: "0.25",
    provider: "PG SOFT",
  },
  {
    name: "Gladiator's Glory",
    rtp: "96.75%",
    maxExposure: "x5000",
    minBet: "0.2",
    provider: "PG SOFT",
  },
  {
    name: "Guardians of Ice & Fire",
    rtp: "96.70%",
    maxExposure: "x6917",
    minBet: "0.2",
    provider: "PG SOFT",
  },
  {
    name: "Hawaiian Tiki",
    rtp: "96.76%",
    maxExposure: "x1274",
    minBet: "0.2",
    provider: "PG SOFT",
  },
  {
    name: "Heist Stakes",
    rtp: "96.72%",
    maxExposure: "x3071",
    minBet: "0.2",
    provider: "PG SOFT",
  },
  {
    name: "Hip Hop Panda",
    rtp: "95.75%",
    maxExposure: "x572",
    minBet: "0.3",
    provider: "PG SOFT",
  },
  {
    name: "Honey Trap of Diao Chan",
    rtp: "96.96%",
    maxExposure: "x20230",
    minBet: "0.3",
    provider: "PG SOFT",
  },
  {
    name: "Hood vs Wolf",
    rtp: "95.39%",
    maxExposure: "x360",
    minBet: "0.3",
    provider: "PG SOFT",
  },
  {
    name: "Hotpot",
    rtp: "95.83%",
    maxExposure: "x12352",
    minBet: "0.3",
    provider: "PG SOFT",
  },
  {
    name: "Jack Frost's Winter",
    rtp: "96.70%",
    maxExposure: "x3500",
    minBet: "0.2",
    provider: "PG SOFT",
  },
  {
    name: "Jewels of Prosperity",
    rtp: "96.73%",
    maxExposure: "x5952",
    minBet: "0.25",
    provider: "PG SOFT",
  },
  {
    name: "Journey to the Wealth",
    rtp: "96.39%",
    maxExposure: "x1268",
    minBet: "0.3",
    provider: "PG SOFT",
  },
  {
    name: "Jungle Delight",
    rtp: "96.03%",
    maxExposure: "x2669",
    minBet: "0.2",
    provider: "PG SOFT",
  },
  {
    name: "Jurassic Kingdom",
    rtp: "96.72%",
    maxExposure: "x6684",
    minBet: "0.2",
    provider: "PG SOFT",
  },
  {
    name: "Legend of Hou Yi",
    rtp: "95.78%",
    maxExposure: "x900",
    minBet: "0.3",
    provider: "PG SOFT",
  },
  {
    name: "Legend of Perseus",
    rtp: "96.77%",
    maxExposure: "x7524",
    minBet: "0.2",
    provider: "PG SOFT",
  },
  {
    name: "Legendary Monkey King",
    rtp: "96.71%",
    maxExposure: "x6030",
    minBet: "0.2",
    provider: "PG SOFT",
  },
  {
    name: "Leprechaun Riches",
    rtp: "97.35%",
    maxExposure: "x9893",
    minBet: "0.2",
    provider: "PG SOFT",
  },
  {
    name: "Lucky Clover Riches",
    rtp: "96.77%",
    maxExposure: "x7500",
    minBet: "0.2",
    provider: "PG SOFT",
  },
  {
    name: "Lucky Neko",
    rtp: "96.73%",
    maxExposure: "x5527",
    minBet: "0.2",
    provider: "PG SOFT",
  },
  {
    name: "Lucky Piggy",
    rtp: "96.79%",
    maxExposure: "x3687",
    minBet: "0.2",
    provider: "PG SOFT",
  },
  {
    name: "Mafia Mayhem",
    rtp: "96.76%",
    maxExposure: "x10000",
    minBet: "0.2",
    provider: "PG SOFT",
  },
  {
    name: "Mahjong Ways",
    rtp: "96.92%",
    maxExposure: "x2893",
    minBet: "0.2",
    provider: "PG SOFT",
  },
  {
    name: "Mahjong Ways 2",
    rtp: "96.95%",
    maxExposure: "x1708",
    minBet: "0.2",
    provider: "PG SOFT",
  },
  {
    name: "Majestic Treasures",
    rtp: "96.68%",
    maxExposure: "x5236",
    minBet: "0.2",
    provider: "PG SOFT",
  },
  {
    name: "Mask Carnival",
    rtp: "96.70%",
    maxExposure: "x2451",
    minBet: "0.2",
    provider: "PG SOFT",
  },
  {
    name: "Medusa",
    rtp: "95.29%",
    maxExposure: "x550",
    minBet: "0.3",
    provider: "PG SOFT",
  },
  {
    name: "Medusa II",
    rtp: "94.96%",
    maxExposure: "x529",
    minBet: "0.3",
    provider: "PG SOFT",
  },
  {
    name: "Mermaid Riches",
    rtp: "96.71%",
    maxExposure: "x3513",
    minBet: "0.2",
    provider: "PG SOFT",
  },
  {
    name: "Midas Fortune",
    rtp: "96.73%",
    maxExposure: "x2138",
    minBet: "0.2",
    provider: "PG SOFT",
  },
  {
    name: "Mr. Hallow-Win",
    rtp: "95.86%",
    maxExposure: "x1964",
    minBet: "0.3",
    provider: "PG SOFT",
  },
  {
    name: "Muay Thai Champion",
    rtp: "97.38%",
    maxExposure: "x3120",
    minBet: "0.2",
    provider: "PG SOFT",
  },
  {
    name: "Mystic Potion",
    rtp: "96.73%",
    maxExposure: "x10000",
    minBet: "0.2",
    provider: "PG SOFT",
  },
  {
    name: "Mystical Spirits",
    rtp: "96.75%",
    maxExposure: "x5000",
    minBet: "0.2",
    provider: "PG SOFT",
  },
  {
    name: "Ninja Raccoon Frenzy",
    rtp: "96.81%",
    maxExposure: "x2500",
    minBet: "0.2",
    provider: "PG SOFT",
  },
  {
    name: "Ninja vs Samurai",
    rtp: "97.44%",
    maxExposure: "x2610",
    minBet: "0.2",
    provider: "PG SOFT",
  },
  {
    name: "Opera Dynasty",
    rtp: "96.74%",
    maxExposure: "x8841",
    minBet: "0.2",
    provider: "PG SOFT",
  },
  {
    name: "Oriental Prosperity",
    rtp: "96.75%",
    maxExposure: "x3269",
    minBet: "0.2",
    provider: "PG SOFT",
  },
  {
    name: "Phoenix Rises",
    rtp: "96.70%",
    maxExposure: "x2990",
    minBet: "0.2",
    provider: "PG SOFT",
  },
  {
    name: "Piggy Gold",
    rtp: "95.86%",
    maxExposure: "x5000",
    minBet: "0.25",
    provider: "PG SOFT",
  },
  {
    name: "Pinata Wins",
    rtp: "96.75%",
    maxExposure: "x5000",
    minBet: "0.2",
    provider: "PG SOFT",
  },
  {
    name: "Plushie Frenzy",
    rtp: "94.82%",
    maxExposure: "x505",
    minBet: "0.3",
    provider: "PG SOFT",
  },
  {
    name: "Prosperity Fortune Tree",
    rtp: "96.77%",
    maxExposure: "x1513",
    minBet: "0.2",
    provider: "PG SOFT",
  },
  {
    name: "Prosperity Lion",
    rtp: "95.77%",
    maxExposure: "x727",
    minBet: "0.27",
    provider: "PG SOFT",
  },
  {
    name: "Queen of Bounty",
    rtp: "96.74%",
    maxExposure: "x7576",
    minBet: "0.2",
    provider: "PG SOFT",
  },
  {
    name: "Raider Jane's Crypt of Fortune",
    rtp: "96.75%",
    maxExposure: "x4742",
    minBet: "0.2",
    provider: "PG SOFT",
  },
  {
    name: "Rave Party Fever",
    rtp: "96.73%",
    maxExposure: "x4699",
    minBet: "0.2",
    provider: "PG SOFT",
  },
  {
    name: "Reel Love",
    rtp: "96.96%",
    maxExposure: "x3446",
    minBet: "0.2",
    provider: "PG SOFT",
  },
  {
    name: "Rise of Apollo",
    rtp: "96.78%",
    maxExposure: "x6171",
    minBet: "0.2",
    provider: "PG SOFT",
  },
  {
    name: "Rooster Rumble",
    rtp: "96.75%",
    maxExposure: "x3158",
    minBet: "0.2",
    provider: "PG SOFT",
  },
  {
    name: "Safari Wilds",
    rtp: "96.75%",
    maxExposure: "x5000",
    minBet: "0.2",
    provider: "PG SOFT",
  },
  {
    name: "Santa's Gift Rush",
    rtp: "96.36%",
    maxExposure: "x689",
    minBet: "0.3",
    provider: "PG SOFT",
  },
  {
    name: "Secrets of Cleopatra",
    rtp: "96.74%",
    maxExposure: "x8649",
    minBet: "0.2",
    provider: "PG SOFT",
  },
  {
    name: "Shaolin Soccer",
    rtp: "96.93%",
    maxExposure: "x1662",
    minBet: "0.25",
    provider: "PG SOFT",
  },
  {
    name: "Shark Bounty",
    rtp: "96.73%",
    maxExposure: "x5000",
    minBet: "0.2",
    provider: "PG SOFT",
  },
  {
    name: "Songkran Splash",
    rtp: "96.69%",
    maxExposure: "x5000",
    minBet: "0.2",
    provider: "PG SOFT",
  },
  {
    name: "Speed Winner",
    rtp: "96.72%",
    maxExposure: "x8345",
    minBet: "0.2",
    provider: "PG SOFT",
  },
  {
    name: "Spirited Wonders",
    rtp: "96.70%",
    maxExposure: "x7388",
    minBet: "0.2",
    provider: "PG SOFT",
  },
  {
    name: "Super Golf Drive",
    rtp: "96.78%",
    maxExposure: "x8000",
    minBet: "0.2",
    provider: "PG SOFT",
  },
  {
    name: "Supermarket Spree",
    rtp: "96.71%",
    maxExposure: "x2309",
    minBet: "0.2",
    provider: "PG SOFT",
  },
  {
    name: "Symbols of Egypt",
    rtp: "95.71%",
    maxExposure: "x1080",
    minBet: "0.27",
    provider: "PG SOFT",
  },
  {
    name: "Thai River Wonders",
    rtp: "96.71%",
    maxExposure: "x8716",
    minBet: "0.2",
    provider: "PG SOFT",
  },
  {
    name: "The Great Icescape",
    rtp: "96.33%",
    maxExposure: "x7963",
    minBet: "0.25",
    provider: "PG SOFT",
  },
  {
    name: "The Queen's Banquet",
    rtp: "96.71%",
    maxExposure: "x9071",
    minBet: "0.2",
    provider: "PG SOFT",
  },
  {
    name: "Totem Wonders",
    rtp: "96.73%",
    maxExposure: "x2500",
    minBet: "0.2",
    provider: "PG SOFT",
  },
  {
    name: "Treasures of Aztec",
    rtp: "96.71%",
    maxExposure: "x9071",
    minBet: "0.2",
    provider: "PG SOFT",
  },
  {
    name: "Tree of Fortune",
    rtp: "95.01%",
    maxExposure: "x213",
    minBet: "0.3",
    provider: "PG SOFT",
  },
  {
    name: "Tsar Treasures",
    rtp: "96.75%",
    maxExposure: "x2500",
    minBet: "0.2",
    provider: "PG SOFT",
  },
  {
    name: "Ultimate Striker",
    rtp: "96.77%",
    maxExposure: "x8000",
    minBet: "0.2",
    provider: "PG SOFT",
  },
  {
    name: "Vampire's Charm",
    rtp: "96.75%",
    maxExposure: "x1696",
    minBet: "0.2",
    provider: "PG SOFT",
  },
  {
    name: "Ways of the Qilin",
    rtp: "96.69%",
    maxExposure: "x7106",
    minBet: "0.2",
    provider: "PG SOFT",
  },
  {
    name: "WereWolf's Hunt",
    rtp: "96.75%",
    maxExposure: "x10000",
    minBet: "0.2",
    provider: "PG SOFT",
  },
  {
    name: "Wild Ape #3258",
    rtp: "96.74%",
    maxExposure: "x10000",
    minBet: "0.2",
    provider: "PG SOFT",
  },
  {
    name: "Wild Bandito",
    rtp: "96.73%",
    maxExposure: "x2525",
    minBet: "0.2",
    provider: "PG SOFT",
  },
  {
    name: "Wild Bounty Showdown",
    rtp: "96.75%",
    maxExposure: "x5000",
    minBet: "0.2",
    provider: "PG SOFT",
  },
  {
    name: "Wild Coaster",
    rtp: "96.71%",
    maxExposure: "x16465",
    minBet: "0.2",
    provider: "PG SOFT",
  },
  {
    name: "Wild Fireworks",
    rtp: "96.75%",
    maxExposure: "x1356",
    minBet: "0.2",
    provider: "PG SOFT",
  },
  {
    name: "Wild Heist Cashout",
    rtp: "96.77%",
    maxExposure: "x2500",
    minBet: "0.2",
    provider: "PG SOFT",
  },
  {
    name: "Win Win Fish Prawn Crab",
    rtp: "96.72%",
    maxExposure: "x3672",
    minBet: "0.2",
    provider: "PG SOFT",
  },
  {
    name: "Win Win Won",
    rtp: "94.14%",
    maxExposure: "x2600",
    minBet: "0.25",
    provider: "PG SOFT",
  },
  {
    name: "Yakuza Honor",
    rtp: "96.75%",
    maxExposure: "x2500",
    minBet: "0.2",
    provider: "PG SOFT",
  },
  {
    name: "Wings of Iguazu",
    rtp: "96.75%",
    maxExposure: "x2000",
    minBet: "0.2",
    provider: "PG SOFT",
  },
  {
    name: "Three Crazy Piggies",
    rtp: "96.72%",
    maxExposure: "x2500",
    minBet: "0.2",
    provider: "PG SOFT",
  },
  {
    name: "Zombie Outbreak",
    rtp: "96.76%",
    maxExposure: "x5000",
    minBet: "0.2",
    provider: "PG SOFT",
  },
];
